export const colors = {
  capColor: [
    {name: "brown", color: "#824920"},
    {name: "buff", color: "#F0DC82"},
    {name: "cinnamon", color: "#D2691E"},
    {name: "gray", color: "#BFBFBF"},
    {name: "green", color: "#00A550"},
    {name: "pink", color: "#FF91AF"},
    {name: "purple", color: "#A400A4"},
    {name: "red", color: "#CC0000"},
    {name: "white", color: "#FFFFFF"},
    {name: "yellow", color: "#FFC40C"},
  ],
  gillColor: [
    {name: "brown", color: "#824920"},
    {name: "buff", color: "#F0DC82"},
    {name: "chocolate", color: "#68574B"},
    {name: "gray", color: "#BFBFBF"},
    {name: "green", color: "#00A550"},
    {name: "orange", color: "#FF8B28"},
    {name: "pink", color: "#FF91AF"},
    {name: "purple", color: "#A400A4"},
    {name: "white", color: "#FFFFFF"},
    {name: "yellow", color: "#FFC40C"},
  ],
  ringType: [
    {name: "cobwebby", color: "#FFFFFF"},
    {name: "evanescent", color: "#FFFFFF"},
    {name: "flaring", color: "#FFFFFF"},
    {name: "large", color: "#FFFFFF"},
    {name: "zone", color: "#FFFFFF"},
    {name: "pendant", color: "#FFFFFF"},
    {name: "sheathing", color: "#FFFFFF"},
    {name: "none", color: "#FFFFFF"},
  ],
  stalkColorAbv: [
    {name: "brown", color: "#824920"},
    {name: "buff", color: "#F0DC82"},
    {name: "orange", color: "#FF8B28"},
    {name: "cinnamon", color: "#D2691E"},
    {name: "gray", color: "#BFBFBF"},
    {name: "pink", color: "#FF91AF"},
    {name: "red", color: "#CC0000"},
    {name: "white", color: "#FFFFFF"},
    {name: "yellow", color: "#FFC40C"},
  ],
  stalkColorBlw: [
    {name: "brown", color: "#824920"},
    {name: "buff", color: "#F0DC82"},
    {name: "orange", color: "#FF8B28"},
    {name: "cinnamon", color: "#D2691E"},
    {name: "gray", color: "#BFBFBF"},
    {name: "pink", color: "#FF91AF"},
    {name: "red", color: "#CC0000"},
    {name: "white", color: "#FFFFFF"},
    {name: "yellow", color: "#FFC40C"},
  ],
  stalkColor: [
    {name: "brown", color: "#824920"},
    {name: "buff", color: "#F0DC82"},
    {name: "orange", color: "#FF8B28"},
    {name: "cinnamon", color: "#D2691E"},
    {name: "gray", color: "#BFBFBF"},
    {name: "pink", color: "#FF91AF"},
    {name: "red", color: "#CC0000"},
    {name: "white", color: "#FFFFFF"},
    {name: "yellow", color: "#FFC40C"},
  ],
  veilColor: [
    {name: "brown", color: "#824920"},
    {name: "orange", color: "#FF8B28"},
    {name: "white", color: "#FFFFFF"},
    {name: "yellow", color: "#FFC40C"},
  ],
  bruise: [
    {name: "yes", color: "#FFFFFF"},
    {name: "no", color: "#FFFFFF"},
  ],
};
