export const colors = {
  capColor: [
    {name: "brown", color: "#824920", tag: "n"},
    {name: "buff", color: "#F0DC82", tag: "b"},
    {name: "cinnamon", color: "#D2691E", tag: "c"},
    {name: "gray", color: "#BFBFBF", tag: "g"},
    {name: "green", color: "#00A550", tag: "r"},
    {name: "pink", color: "#FF91AF", tag: "p"},
    {name: "purple", color: "#A400A4", tag: "u"},
    {name: "red", color: "#CC0000", tag: "e"},
    {name: "white", color: "#FFFFFF", tag: "w"},
    {name: "yellow", color: "#FFC40C", tag: "y"},
  ],
  gillColor: [
    {name: "black", color: "black", tag: "k"},
    {name: "brown", color: "#824920", tag: "n"},
    {name: "buff", color: "#F0DC82", tag: "b"},
    {name: "chocolate", color: "#68574B", tag: "h"},
    {name: "gray", color: "#BFBFBF", tag: "g"},
    {name: "green", color: "#00A550", tag: "r"},
    {name: "orange", color: "#FF8B28", tag: "o"},
    {name: "pink", color: "#FF91AF", tag: "p"},
    {name: "purple", color: "#A400A4", tag: "u"},
    {name: "red", color: "#CC0000", tag: "e"},
    {name: "white", color: "#FFFFFF", tag: "w"},
    {name: "yellow", color: "#FFC40C", tag: "y"},
  ],
  ringType: [
    {name: "cobwebby", color: "#FFFFFF", tag: "c"},
    {name: "evanescent", color: "#FFFFFF", tag: "e"},
    {name: "flaring", color: "#FFFFFF", tag: "f"},
    {name: "large", color: "#FFFFFF", tag: "l"},
    {name: "zone", color: "#FFFFFF", tag: "z"},
    {name: "pendant", color: "#FFFFFF", tag: "p"},
    {name: "sheathing", color: "#FFFFFF", tag: "s"},
    {name: "none", color: "#FFFFFF", tag: "n"},
  ],
  stalkColorAbv: [
    {name: "brown", color: "#824920", tag: "n"},
    {name: "buff", color: "#F0DC82", tag: "b"},
    {name: "orange", color: "#FF8B28", tag: "o"},
    {name: "cinnamon", color: "#D2691E", tag: "c"},
    {name: "gray", color: "#BFBFBF", tag: "g"},
    {name: "pink", color: "#FF91AF", tag: "p"},
    {name: "red", color: "#CC0000", tag: "e"},
    {name: "white", color: "#FFFFFF", tag: "w"},
    {name: "yellow", color: "#FFC40C", tag: "y"},
  ],
  stalkColorBlw: [
    {name: "brown", color: "#824920", tag: "n"},
    {name: "buff", color: "#F0DC82", tag: "b"},
    {name: "orange", color: "#FF8B28", tag: "o"},
    {name: "cinnamon", color: "#D2691E", tag: "c"},
    {name: "gray", color: "#BFBFBF", tag: "g"},
    {name: "pink", color: "#FF91AF", tag: "p"},
    {name: "red", color: "#CC0000", tag: "e"},
    {name: "white", color: "#FFFFFF", tag: "w"},
    {name: "yellow", color: "#FFC40C", tag: "y"},
  ],
  stalkColor: [
    {name: "brown", color: "#824920", tag: "n"},
    {name: "buff", color: "#F0DC82", tag: "b"},
    {name: "orange", color: "#FF8B28", tag: "o"},
    {name: "cinnamon", color: "#D2691E", tag: "c"},
    {name: "gray", color: "#BFBFBF", tag: "g"},
    {name: "pink", color: "#FF91AF", tag: "p"},
    {name: "red", color: "#CC0000", tag: "e"},
    {name: "white", color: "#FFFFFF", tag: "w"},
    {name: "yellow", color: "#FFC40C", tag: "y"},
  ],
  veilColor: [
    {name: "brown", color: "#824920", tag: "n"},
    {name: "orange", color: "#FF8B28", tag: "o"},
    {name: "white", color: "#FFFFFF", tag: "w"},
    {name: "yellow", color: "#FFC40C", tag: "y"},
  ],
  bruise: [
    {name: "yes", color: "#FFFFFF", tag: "t"},
    {name: "no", color: "#FFFFFF", tag: "f"},
  ],
};
